Add discord rich presence
DryByte/aos.dll pull request #13
Opened 2024-02-21 22:13 UTC by yobonez

This PR contains only clientside info for rich presence.
Requires further work for getting serverside information.

2024-03-15 23:29 UTC, DryByte requested changes

2024-03-15 23:33 UTC, yobonez commented on Source/Mod/RichPresence/Presence.c
> +void initrichpresence() {
Ok, i was using your naming convention of initsomething() function names, Maybe change initmodloader and others in your next commits to be consistent.

2024-03-15 23:50 UTC, DryByte commented on Source/Mod/RichPresence/Presence.c
> +void initrichpresence() {
Oh i didn't notice i did that, but yes, its supposed to be like normal snake case.

2024-03-27 20:35 UTC, DryByte approved these changes

2024-03-27 20:35 UTC, merged